### PR TITLE
New auro-avatar component

### PR DESCRIPTION
**Pull request by blackfalcon**
# Alaska Airlines Pull Request

## Summary:

This PR is for the development of the new auro-avatar web component. 

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by blackfalcon** [comment]
Work is ready to merge. A version is released with http://sprint-20.surge.sh/ for design review.

**Comment by blackfalcon** [comment]
Updates posted based on feedback http://sprint-20.surge.sh/

**Comment by blackfalcon** [comment]
Design review approved for release.

**Review by ecommerceUXdesign — APPROVED** [review]

**Pull request merged**
