### PR TITLE
Apply latest token ds-auro-icon-size #66

### PR DESCRIPTION
**Pull request by rmenner**
# Alaska Airlines Pull Request

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

## Summary by Sourcery

Enhancements:
- Update the CSS to use a CSS variable for icon size, improving maintainability.

### CODE REVIEW

**Review by jordanjones243 — CHANGES_REQUESTED** [review]
There is an issue with how the tail icon is now rendering. If you compare the localhost tail icons to the one on the docsite, you can see that some of the icon is cut off.

I think the issue is tied to the fact that we now use the `--ds-auro-icon-size` token for now both the height and width, when previously the `118%` was only allocated towards width in this repo.

**Comment by rmenner** [comment]
> There is an issue with how the tail icon is now rendering. If you compare the localhost tail icons to the one on the docsite, you can see that some of the icon is cut off.
> 
> I think the issue is tied to the fact that we now use the `--ds-auro-icon-size` token for now both the height and width, when previously the `118%` was only allocated towards width in this repo.

Ended up having change all the values to make it match the existing styles of released version on docs

**Review by jordanjones243 — CHANGES_REQUESTED** [review]
Need to run build to update `min.js` files

**Comment by rmenner** [comment]
> Need to run build to update `min.js` files

Built it before pushing. But I double checked in case I missed something. No changes to push after rebuild.

**Review by jordanjones243 — APPROVED** [review]

**Pull request merged**
